---
- name: Check if Apache is installed
  stat:
    path: "{{ apache_security_conf }}"
  register: apache
  ignore_errors: True

- name: Install Apache packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - apache2-utils
    - apache2-dev
  when: apache.stat.exists == false

- name: Enable required Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - actions
    - rewrite
    - proxy_http
  when: apache.stat.exists == false

- name: Ensure APACHE_RUN_USER is set to the expected user
  lineinfile:
    dest: "{{ apache_envvars }}"
    regexp: "export APACHE_RUN_USER=www-data"
    line: "export APACHE_RUN_USER={{ user }}"
  when: apache.stat.exists == false

- name: Fix the POODLE SSL v3 vulnerability
  lineinfile:
    dest: "{{ apache_ssl_mod }}"
    regexp: "SSLProtocol all"
    line: "\tSSLProtocol all -SSLv2 -SSLv3"
  when: apache.stat.exists == false

- name: Ensure Apache is started
  service:
    name: apache2
    enabled: yes
    state: started
